### ISSUE TITLE
Humason New Observations, Questions, Updates

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#11] opened 2023-02-16 04:51 UTC
I found some other things of interest tonight for fyi...

1. Sometimes Read in or load a target such as NGC 2023 for some reason loads the "Sun" instead. I delete it and try again as the workaround. Eventually, it goes away. Wierd.
2. Can't loop any more than 100 images in target tab. I would think 120 or 180 would be nice.
3. Autoflip did not work for me. Had to do it manually,  How does it work specifically. Is it speciffic to SB mounts or mght it work for Losmandy G11s as well.
4. Can the user enter his own path or just use TSX for storing files as an option. I can look into this if your slammed.
5. Do you have any example scripts used in the session tab that could be used to park the scope at end of session in its park position using the hardpark sb class instead of softpark. The checkbox in manual for park does a softpark I believe as I tested last night.

**Comment by rrskybox** [comment] 2023-02-16 14:35
1. I'll have to look at it.  Is there anything else running concurrently, e.g. Image Planner?
2. Easy -- never was a reason for a limitation.
3. Been a while since I've looked at Autoflip.  It's somewhat complicated.  There may be a reason why it's limited to Paramounts.  I'll let you know.
4. Although nothing is ever perfect, there are some reasons why I chose the current file structure, mostly having to do with making it easier to automate the post-processing of images.  As always, feel free to diverge -- that's one reason that I made the code public.  Maybe there's a benefit that I don't recognize.
5. Attached is my shutdown script to play with.  It's got a lot more than you're asking for, but it gives you the gist.

[ShutDown.txt](https://github.com/rrskybox/Humason/files/10756983/ShutDown.txt)

**Comment by rrskybox** [comment] 2023-02-16 15:01
Re Item 2:  Done.  I'll push an update sometime today.
Re Item 3:  For autoflip to work, a mount driver must return the current side of pier, and, TSX must pass it through.  Obviously Paramounts do, but I couldn't tell you about any other mounts.  Without knowing the current side of pier for a mount, it's almost impossible to reliably know when a target has crossed the meridian, given all the other things that might be going on.  At least, it's been beyond me and lord knows I've tried.

**Comment by rrskybox** [comment] 2023-02-16 15:58
I don't remember where this was brought up, but I've published the application that mentioned re assembling fits files for image processing.  You had said you might want a peek.  

[https://github.com/rrskybox/PreStack/tree/master]

**Comment by rrskybox** [comment] 2023-02-17 23:42
Re Item 3:  I got increasingly nervous about the comment on AutoFlip and using a Gemini mount.  I had not considered what to do about a mount driver that didn't report Side of Pier correctly, or if at all.  So...  I added a checkbox in the Sessions tab to enable/disable an automatic meridian flip.  It is adjacent the button where you can check to see if the mount driver is reporting Side of Pier correctly.  Humason will not flip the mount if that is not enabled.  Build 233.

**Comment by astromiester1** [comment] 2023-02-18 21:32
Hi Rick, thanks for taking at look at this.. Gotta wait till a good night to test out latest build.

Regarding item 5, is this a script which can be loaded in humanson session tab such as the At session end or dawn browse option? It looks like C# code needing to be compiled. Is your session tab expecting phython like or java script?

Regarding item4. My goal is to just let the control for image dump to be in the hands of TSX. I can't seem to simulate this but thought the easiest thing was to comment out some of your saving command lines. I was thinking of doing this in the tsxlinks. cs, sequence.cs, imagefilemanger.cs or imaging.cs file. Since, I didn't write the code, can you recommend the least path of code interference where I can do this as I don't want to break anything.  My first stab was to change AutoSaveOn = 0 to 1 in correct places along with commenting out  tsxi.Path = targetImageDataPath; ,  tsxi.Save();   lg.LogIt("Image saved: " + targetImageDataPath); from the SaveLightImage class inside the imageFilesManager.cs file... Any thoughts or suggestions.

Thanks Dale

**Comment by rrskybox** [comment] 2023-02-19 03:58
Item 4:  You pretty much have the changes that are required figured out.  Just comment out all occurrences of "AutoSaveOn = 0" in imaging.cs.  Then comment out any calls to ImageFileManager.SaveLightImage.  That should do it... I think.

Item 5:  Humason will launch any standalone executable (*.exe, *.vbs, etc) that you link to.  It would be silly, but you could link to Notepad.exe and launch it if you wanted.  Anything probably works as long as it's an executable.  If you wanted to write something in Python then that's fine too -- just link to its compiled executable.   The code I sent you is just the source that I compile into the executable that I use to close my observatory.  Hope that makes sense.

**Comment by astromiester1** [comment] 2023-02-19 17:54
Hi Rick, did some furthur studying of the code. It appears no change in AutoSaveOn is required in your code but to leave as is as it appears not to be used for result image but for everything needed upto the start sequence of final imaging. So, I left AutoSaveOn alone and moved on to looking at SaveLightImage call to ImageFilemanger.cs residing in sequence.cs(lines 619 to 637).  However, this too seems to be apart of side of pier and flats. So, I left those alone. Now there is another term of interest. AutoSave not AutoSaveOn which is in sequence.cs which is set to 0. Maybe, thats the term to change to 1 which is part of AstroImage class line 587. Based on this I then tried to cut off the other saving aspect from the ImageFileManager.cs file searching "Image saved" from log entry. This put me on line 74 of that file. So, I commented out the tsxi.Path and tsxi.save(); lines 72 and 73.  Does this sound reasonable. Might be missing something. Can't test yet either unless maybe in simulator bypassing platesolving somehow in the code. Feedback?

**Comment by rrskybox** [comment] 2023-02-20 00:31
1. Yes, you want to set AutoSave = 1 in Sequencer.cs Line 587, but also AutoSaveOn = 1 in Imaging.cs Line 329 and 455 (for autosaving Flats).   I don't remember why I didn't use the AstroImage class for imaging and saving flats.  I may go back and revisit that although I hate to mess with something seems to be working.

2. And then, yes, you want to comment out lines 72-73 and lines 122-123 in ImageFileManager -- or, you could comment out the 5 references to ImageFileManager methods in Sequencer.cs and Imaging.cs (which is the cleaner solution IMHO).  

The remaining 5 "AutoSave=0" instructions are for turning off saving autoguider images while autoguiding.  You could reverse those as well if you're interested in saving those images.  Those places that I specifically set AutoSaveOn to 1 are places where I had to save the image for plate solving, calibration or optimization purposes -- there's no reason not to have TSX save them in the TSX directories as they are throwaways -- that's one benefit of saving the images that you want to keep externally to the Software Bisque directory -- you can delete those saved in the Camera Autosave folder en mass without worry -- primarily optimization, focus and CLS images.

**Comment by rrskybox** [comment] 2023-02-22 17:21
I think running on diverging code bases is a recipe for disaster.  So, although I still think this is a step backwards, I added a configuration option (in the Options window) to turn on TSX AutoSave.   I also ended up refactoring some of the imaging code so I could have screwed something else up there.  Build 235 should carry the changes once I finish testing it.

1. Still looking at it.
2. My first guess is that you've got hot pixels.  You probably need to AutoDark or Full Reduction to get rid of them.  Hot pixel removal is something built into @Focus3.
3. When you say "calibration numbers", are you referring to the autoguider set up (exposure, etc) or the autoguider calibration vectors?  Need some more details here.
4. The "edge margin" is the minimum number of pixels that the guide star must be off from the edge.  Try 32 or 64 for an edge margin.  It doesn't need to be any wider than half your tracking box really.  I'll look, but I'm not sure my search algorithm doesn't go bonkers with an edge margin greater than half the overall image width.  I probably should throw out an exception error if that's tried.
5. Worth some discussion.  I purposely leave the camera connected so it doesn't start warming up for two reasons.  The first is that some older models like to have their temperature raised gracefully.  The second is that I like to keep the temperature down in case flats are done manually after the session.  That said, I really don't have strong feelings here.  Thoughts?

**Comment by astromiester1** [comment] 2023-02-22 20:53
Sounds good.. I will wait for build 235.

2, Will give that a shot. Focus3 did not ask for darks or ask me to cover my scope as I used no calibration frames and worked but took forever.

3. The autoguider calibration numbers that you type in the windows for x and y near the calibrate and autocalibrate buttons. 

4. Will give that a try.

5. I would think if you want to do multiple sessions and will be around when it finishes. But, if you know your going to bed and run the last session I would think shuting as much down as possible makes sense. Just my 2 cents.

**Comment by rrskybox** [comment] 2023-02-23 04:52
#1 -- This is yet another reason Humason was designed to do its own file saving.  For file naming, TSX applies the "name" used in the last slew.  TSX also enters that "name" in the FITS header for the OBJECT field.  Humason uses RA/Dec coordinates, not target names for slewing.  The target "name" that TSX uses for any slew using RA/Dec coordinates is "Star Chart Center".  This is why that shows up in the TSX AutoSave file name (and its FITS header).  The reason why Humason uses RA/Dec coordinates rather than catalog name is that 1) many of the non-stellar catalogs have inaccuracies, and 2) most of the time a user will adjust the position of their FOV at least slightly to best frame the target and/or center a star for autoguiding.  So, if one wants to use TSX AutoSave, then you're pretty well stuck with its limitations.   Note that this is all fixable, of course.  But, by the time you've got that all sorted out then you've pretty much done what Humason already does -- just put it in a different directory.  Frankly, I'm not aware of any other sequencer automation that uses TSX and doesn't utilize an independent file structure.
#2 -- AG3 is a field focus algorithm.  I'm pretty sure that the developer scrubbed out hot pixels in the process.  Not so in AG2.
#3 -- Omitted in code for some reason, hopefully not a good one.  Fixed now.  
#5 -- Changed code to disconnect all devices at end of session, if a shut down script as not been configured.

Still testing the latest version.

**Comment by rrskybox** [comment] 2023-02-23 15:48
Build 235 checked out and published.  Will close this issue up at least for now.

**Comment by astromiester1** [comment] 2023-02-23 19:21
Just an fyi...More testing last night with observations above...

1. Autoflip seems to work very nicely...I will try V235 on the next decent night.
2. Do you use AF2 successfully and if so was the dark frame subtract how it got it to work?

**Comment by rrskybox** [comment] 2023-02-23 21:46
I use AF2 exclusively, but with AutoDark enabled. It helps. I added an option in V235 that allows you to choose the focus reduction independently of the other imaging.  That may be useful to you.

**Comment by astromiester1** [comment] 2023-02-24 22:01
Some observations so far using V235.

6. Need to do more testing but it appears after a successful guider calibration, the autoguider does not pick a star, fails and stops the whole script and shuts down. Need to try it again as it might be an isolated case.. Standbye, will do more testing. The only way I got past this was to select the star for the script. This could be the ADU setting be too low perhaps in my setup. I had it at 1000 ADU and bumped it up to 1500 ADU. So, if it fails I recall, you still allowed the script to image, did you change the flow on this as it shut down once it didn't guide.

7.  This one is really strange and will test again for repeatability. I set 60 image looping at 60 secs set for TSX saving and once 60 images where completed the status bar showed only have way done and continued to image into the 70s before I shut it down assuming it would go to 120 if I didn't stop it.  Will do more testing to verify.

**Comment by rrskybox** [comment] 2023-02-25 01:28
Issue #6. Hmm...  The ADU number only sets a target to optimize a guide star exposure time.  I think the question is why isn't Humason finding a guide star.  If calibration is successful, then TSX must have been able to find one.  The limitation of TSX's built in  is that it will "find" stars that are too close to the edge or too close to other stars (or hot pixels).  On the other hand, Humason's method gets confused if there are too many stars in the field.  This is where using the Guide tab as a diagnostic can help.

1. Slew the scope to your target.  (Set the Autoguide Reduction type to AutoDark if you can.)
2. Set the default guider exposure to 1 second.
3. Click on "Find Star".  Monitor the TSX guider image produced.  If there are no stars visible, then increase the initial exposure by a second. Try again.
4. When a star is "found", then check the coordinates on the autoguider image to see if it really is at the right place.  If so, continue.
5. Click on "Optimize".  A number of images will be taken with different exposures, attempting to adjust the light source to meet the ADU requirement.  If it's too dim, then the method defaults to the maximum exposure time.  If it's too bright, then the method halts at the minimum exposure time.
6. Click on "Calibrate".  Let it run the its routine.  Should work.
7.Click on "Autoguide" and check TSX graphs for reasonable guider action.
8. If everything works with these individual steps, then you are dialed in and ready to go for any session with this set up.

This is the basic workflow that Humason run's through when operating, so if it breaks at any one of these steps you'll know where the problem is.  Let me know.

Issue #8.  Look to see if you have two filters scheduled for each loop.  Might be the problem.

**Comment by rrskybox** [comment] 2023-02-27 23:28
#7 -- That makes sense.  Changing the name won't automatically drop the filter.  After setup, Humason manages filters by filter index for each imaging sequence, not by name.  That's because that's how TSX does it.  Not a good reason; just a reason.

#8 -- I don't follow the DSLR posts much, but I seem to recall several recently on the TSX Pro forum that had something to do with something similar.  One post is [here](https://www.bisque.com/forums/topic/color-camera-bw-images-saved/).  You might check that out.  First, though, are you able get a good image just using TSX stand-alone (i.e. without Humason)?  If so, we'll take a look to see what Humason might be doing differently and try to get that fixed.

**Comment by astromiester1** [comment] 2023-03-01 02:00
Figured out what was causing #8 . It was the ASCOM driver in TSX not your script.. Once, I switched to native TSX driver the FITS headers had color info in it... It was driving me nuts.. Solved now.. Was a TSX issue.

**Comment by rrskybox** [comment] 2023-03-01 02:54
Good deal.  I think that might have been the gist of the forum post(s) as well.  I' m going to close close this issue up.  If you continue to have difficulties with autoguiding, just open a new comment and we'll get focused on that.

**Closed by rrskybox** 2023-03-01 02:54 UTC
